# Generated by Django 4.2.2 on 2023-07-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviouralquestion',
            name='helpful_tip',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
