# Generated by Django 4.2.2 on 2023-07-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_alter_behaviouralquestion_helpful_tip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='type',
            new_name='name',
        ),
    ]
