# Generated by Django 4.2.2 on 2023-07-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_alter_entry_action_alter_entry_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='situation',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='entry',
            name='task',
            field=models.CharField(max_length=400),
        ),
    ]
