# Generated by Django 4.2.2 on 2023-07-29 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_alter_entry_situation_alter_entry_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='action',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.behaviouralquestion'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='result',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='situation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='task',
            field=models.TextField(),
        ),
    ]
